name: Publish to PyPI

on:
  push:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  main:
    name: sdist + pure wheel
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Create version file
        run: |
          echo "version = '22.12.0+sp1'" > src/_black_version.py

      - name: Set up latest Python
        uses: MatteoH2O1999/setup-python@v4
        with:
          python-version: "*"

      - name: Install latest pip, build, twine
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build twine

      - name: Build wheel and source distributions
        run: python -m build

      - name: Upload wheels as workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: black-wheels
          path: dist/*.whl

  mypyc:
    name: mypyc wheels (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            name: linux-x86_64
          - os: windows-2019
            name: windows-amd64

    steps:
      - uses: actions/checkout@v3
      - name: Create version file
        run: |
          echo "version = '22.12.0+sp1'" > src/_black_version.py

      - name: Build wheels via cibuildwheel
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_ARCHS_MACOS: "${{ matrix.macos_arch }}"

      - name: Upload wheels as workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}-mypyc-wheels
          path: ./wheelhouse/*.whl

  update-stable-branch:
    name: Update stable branch
    needs: [main, mypyc]
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout stable branch
        uses: actions/checkout@v3
        with:
          ref: stable
          fetch-depth: 0

      - name: Update stable branch to release tag & push
        run: |
          git reset --hard ${{ github.event.release.tag_name }}
          git push
